// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://padvpkgevbyasrffrcrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhZHZwa2dldmJ5YXNyZmZyY3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDg4NzEsImV4cCI6MjA2NTUyNDg3MX0.eYC75H9C2Rj4getgczBJaXdjCvWKccV6NWqAxxzPC6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);